<?php
/**
 * Front page template.
 *
 * @package SOP_Writer_Prakash
 */

get_header();

$prakash_image_url = 'https://sop-writer.in/wp-content/uploads/2026/02/prakash-sop-india.jpg';
$contact_status = filter_input(INPUT_GET, 'contact_status', FILTER_SANITIZE_FULL_SPECIAL_CHARS);
?>

<main>
    <section class="hero" id="about">
        <div class="container hero-grid">
            <div class="hero-content">
                <p class="eyebrow">Connect Directly With Your SOP Architect. No Agencies. No Intermediaries</p>
                <h1>Your Academic Fate Is Too High-Consequence to Be Left to Mass-Market Consultants.</h1>
                <p class="hero-subtitle">A 100% profile-led, human-crafted narrative strategy for elite global admissions. We extract your true academic story, engineer your trajectory, and draft documents that stand up to rigorous university scrutiny.</p>
                <div class="cta-row">
                    <a class="btn btn-primary" href="#contact">Secure Free Profile Evaluation</a>
                    <a class="btn btn-secondary" href="#success-vault">View Verified Outcomes</a>
                </div>
                <div class="hero-stats" aria-label="Live counter row">
                    <div><strong>10,041+</strong><span>Applications Handled</span></div>
                    <div><strong>100+</strong><span>Global Programs Supported</span></div>
                    <div><strong>8.5+</strong><span>Years Unbroken Performance Record</span></div>
                </div>
            </div>
            <aside class="hero-aside">
                <div class="portrait-wrap">
                    <img src="<?php echo esc_url($prakash_image_url); ?>" alt="Prakash with award trophy" loading="lazy">
                    <p class="portrait-badge">8.5+ Years of Verified Admission Outcomes.</p>
                </div>
            </aside>
        </div>
    </section>

    <section class="section-soft rescue" id="rescue">
        <div class="container">
            <h2>Did Your Consultant Hand You a Template?</h2>
            <p>Every year, hundreds of students come to us after paying automated admission agencies, only to realize their statement of purpose was generated by a generic template with their name swapped out. If your SOP sounds like an uninspired copy of your resume, it will be flagged or dismissed by the admissions committee.</p>
            <p class="pivot-callout">We run a specialized salvage desk. Whether you are recovering from a previous visa refusal, dealing with an arbitrary academic gap, or attempting to explain a low GPA to a highly competitive university, we rebuild your strategic defense from scratch. No placeholders. No generic filler.</p>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <h2>Strategic Writing &amp; Profiling Services</h2>
            <div class="services-grid">
                <article class="card service-card service-card-wide">
                    <h3>Academic Statement of Purpose (SOP)</h3>
                    <p>Deep-dive narrative profiling that links your past academic projects to your long-term research or market objectives. Zero reliance on generic opening hooks.</p>
                </article>
                <article class="card service-card">
                    <h3>Visa SOP &amp; Letter of Motivation (LOM)</h3>
                    <p>Highly analytical, country-specific documentation focused entirely on mitigating immigration risks, proving financial compliance, and establishing clear home-country ties.</p>
                </article>
                <article class="card service-card">
                    <h3>Institutional Letters of Recommendation (LOR)</h3>
                    <p>Structured to match the explicit psychological profile of the chosen academic or professional referee while preventing repetitive syntax patterns across multiple letters.</p>
                </article>
                <article class="card service-card service-card-tall">
                    <h3>Academic Resumes &amp; CVs</h3>
                    <p>Built specifically for high-stakes admission panels, prioritizing research impact, technical proficiencies, and publications over standard corporate metrics.</p>
                </article>
                <article class="card service-card">
                    <h3>Admission Support &amp; Addendum Essays</h3>
                    <p>Precision editing for short-answer university prompts, scholarship validation essays, and formal explanations for career pivots or structural gaps.</p>
                </article>
            </div>
        </div>
    </section>

    <section class="section-soft" id="authority-matrix">
        <div class="container">
            <h2>The Structural Divide in Application Engineering</h2>
            <div class="table-wrap">
                <table class="comparison-table">
                    <thead>
                        <tr>
                            <th>Traditional Volume Agencies</th>
                            <th>The Prakash Craftsmanship Standard</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><strong>Outsourced to Interns:</strong> Your life story is assigned to low-cost freelance copywriters who lack domain knowledge.</td>
                            <td><strong>Direct Master-Architect Access:</strong> You work 1-on-1 with India&#39;s primary SOP strategist. No middleman, no dilution.</td>
                        </tr>
                        <tr>
                            <td><strong>The Template Assembly Line:</strong> Reuses uniform paragraph blocks, altering only basic data variables like names and colleges.</td>
                            <td><strong>Zero-Template Architecture:</strong> Every narrative is built organically around your specific psychological profile.</td>
                        </tr>
                        <tr>
                            <td><strong>Surface Grammar Check:</strong> Focuses on spelling and punctuation while completely missing visa compliance and program nuances.</td>
                            <td><strong>High-Consequence Strategy:</strong> Fact-checked against rigid visa officer parameters and evolving admissions trends.</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section id="success-vault">
        <div class="container">
            <h2>The Success Vault: True Transformations</h2>
            <div class="vault-grid">
                <article class="card vault-card">
                    <h3>The Low GPA &amp; Career Gap Recovery</h3>
                    <p><strong>The Challenge:</strong> Applicant had a 6.2 CGPA and a 3-year gap in professional employment. Standard agencies suggested applying to lower-tier institutions.</p>
                    <p><strong>The Strategy:</strong> Shifted the core of the SOP away from structural anomalies, focusing entirely on practical open-source project contributions and specific industry certifications.</p>
                    <p><strong>Outcome:</strong> Secured unconditional acceptance to a top-tier European Master of Data Science program.</p>
                </article>
                <article class="card vault-card">
                    <h3>Overcoming a Previous Study Visa Refusal</h3>
                    <p><strong>The Challenge:</strong> Student faced a generic refusal under section 216(1)(b) due to a poorly conceptualized personal statement from a prior agency.</p>
                    <p><strong>The Strategy:</strong> Drafted a highly objective, fact-driven Visa SOP addressing the visa officer&#39;s direct objections with definitive domestic asset matrices.</p>
                    <p><strong>Outcome:</strong> Visa successfully approved for the subsequent intake cycle.</p>
                </article>
            </div>
        </div>
    </section>

    <section class="section-soft ai-hub" id="ai-hub">
        <div class="container ai-grid">
            <div class="card">
                <h2>Evolving the SOP Framework for Modern Evaluation Systems</h2>
                <p>Admissions committees and visa offices now regularly deploy advanced linguistic analysis tools and detection models to flag over-polished, AI-generated content. An SOP that reads like a predictive text model lacks human nuance, specific vulnerability, and strategic focus, greatly increasing the risk of immediate rejection.</p>
            </div>
            <div class="card">
                <h3>High-Intent Queries Addressed</h3>
                <ul class="query-list">
                    <li><strong>How to explain a major academic stream change in an MS application?</strong> We map cross-disciplinary skills logically to prove your transition is intentional, not accidental.</li>
                    <li><strong>How to structure a PhD research proposal statement?</strong> We align your past published work with the specific target laboratory&#39;s ongoing research initiatives.</li>
                    <li><strong>How to secure institutional financial aid through an SOP?</strong> We highlight structural merit and societal impact metrics instead of relying on generic emotional pleas.</li>
                </ul>
            </div>
        </div>
    </section>

    <section id="process">
        <div class="container">
            <h2>The Uncompromised Workflow</h2>
            <ol class="workflow">
                <li>
                    <h3>1. Direct Profiling Consultation</h3>
                    <p>You connect directly with Prakash. No sales reps or account managers. We systematically isolate your profile strengths, clarify career goals, and uncover hidden risks.</p>
                </li>
                <li>
                    <h3>2. Strategic Narrative Architecture</h3>
                    <p>We build a customized thematic framework for your documents, determining the core focus of every single paragraph before drafting begins.</p>
                </li>
                <li>
                    <h3>3. Human-First Iteration &amp; Review</h3>
                    <p>Content is drafted from scratch, followed by direct, comprehensive review sessions to refine language clarity, precision, and persuasive impact.</p>
                </li>
                <li>
                    <h3>4. Final Validation &amp; Hand-off</h3>
                    <p>You receive a polished, ready-to-submit document along with personalized guidance for your interviews and next steps.</p>
                </li>
            </ol>
        </div>
    </section>

    <section class="section-soft" id="contact">
        <div class="container contact-grid">
            <div>
                <h2>Initiate Your Application Audit</h2>
                <p class="section-lead">Talk directly to your SOP editor and build a strategy tailored to your profile.</p>
                <p><strong>Phone / WhatsApp:</strong> <a href="tel:+918447385389">+91 84473 85389</a></p>
                <p><strong>Corporate Email:</strong> <a href="mailto:contact@sop-writer.in">contact@sop-writer.in</a></p>
                <?php if ('success' === $contact_status) : ?>
                    <p class="form-message form-success">Thanks. Your request has been submitted successfully.</p>
                <?php elseif ('failed' === $contact_status) : ?>
                    <p class="form-message form-error">Something went wrong. Please try again or contact us directly.</p>
                <?php endif; ?>
            </div>
            <div class="card contact-form-wrap">
                <form class="contact-form" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post">
                    <input type="hidden" name="action" value="sop_writer_prakash_contact">
                    <?php wp_nonce_field('sop_writer_prakash_contact_nonce', 'sop_writer_prakash_contact_nonce'); ?>

                    <label for="sp-name">Full Name</label>
                    <input id="sp-name" type="text" name="full_name" required>

                    <label for="sp-email">Corporate Email / Personal Email</label>
                    <input id="sp-email" type="email" name="email" required>

                    <label for="sp-phone">WhatsApp Contact Number</label>
                    <input id="sp-phone" type="tel" name="phone" required>

                    <label for="sp-country">Target Destination Country</label>
                    <select id="sp-country" name="target_country" required>
                        <option value="">Select country</option>
                        <option value="Canada">Canada</option>
                        <option value="United States">United States</option>
                        <option value="United Kingdom">United Kingdom</option>
                        <option value="Australia">Australia</option>
                        <option value="Germany">Germany</option>
                        <option value="Ireland">Ireland</option>
                        <option value="Other">Other</option>
                    </select>

                    <label for="sp-program">Intended Academic Program</label>
                    <input id="sp-program" type="text" name="intended_program" required>

                    <label for="sp-message">Describe Current Profile Core Concerns or Past Consultant History</label>
                    <textarea id="sp-message" name="message" rows="4" required></textarea>

                    <button class="btn btn-primary" type="submit">Request Strategic Evaluation</button>
                </form>
            </div>
        </div>
    </section>
</main>

<?php
get_footer();
